url = "https://twitter.com/realDonaldTrump"
obama = "Obama"
russia = "Russia"
collusion = "Collusion"
enemy = "Obama"
archive_url = "https://www.thetrumparchive.com/"
archive_searchbox = ".//input[@aria-label='searchbox']"
donald_xpath = ".//*[text()='Donald J. Trump']"
driver_path = "/Users/reonoldpetrenko/PycharmProjects/TheDonald/chromedriver"
tweet_xpath = ".//div[@class='css-901oao r-jwli3a r-1qd0xha r-a023e6 r-16dba41 r-ad9z0x r-bcqeeo r-bnwqim r-qvutc0']"